(include_subdirs qualified)

(executable
 (enabled_if
  (= %{profile} "dev"))
 (name server)
 (libraries
  dream
  dream_rsc
  demo_shared_native
  demo_nested_router_native
  dream_router_adapter
  server-reason-react.url_native
  server-reason-react.router-runtime-native
  server-reason-react.router-server
  server-reason-react.rsc-native
  react
  reactDOM
  html
  js
  lwt.unix
  str
  unix
  belt
  yojson)
 (preprocess
  (pps
   server-reason-react.ppx
   server-reason-react.melange_ppx
   server-reason-react.rsc-native.ppx
   lwt_ppx)))
