let log _ = ()
let log2 _ _ = ()
let log3 _ _ _ = ()
let log4 _ _ _ _ = ()
let logMany _arr = ()
let info = log
let info2 = log2
let info3 = log3
let info4 = log4
let infoMany = logMany
let error = log
let error2 = log2
let error3 = log3
let error4 = log4
let errorMany = logMany
let warn = log
let warn2 = log2
let warn3 = log3
let warn4 = log4
let warnMany = logMany
let trace () = ()
let timeStart _ = ()
let timeEnd _ = ()
