type t = (string * string) list

let add name item (map : t) =
  match item with Some i -> (name, i) :: map | None -> map

[@@@ocamlformat "disable"]

let make
  ?(azimuth : string option)
  ?(background : string option)
  ?(backgroundAttachment : string option)
  ?(backgroundColor : string option)
  ?(backgroundImage : string option)
  ?(backgroundPosition : string option)
  ?(backgroundRepeat : string option)
  ?(border : string option)
  ?(borderCollapse : string option)
  ?(borderColor : string option)
  ?(borderSpacing : string option)
  ?(borderStyle : string option)
  ?(borderTop : string option)
  ?(borderRight : string option)
  ?(borderBottom : string option)
  ?(borderLeft : string option)
  ?(borderTopColor : string option)
  ?(borderRightColor : string option)
  ?(borderBottomColor : string option)
  ?(borderLeftColor : string option)
  ?(borderTopStyle : string option)
  ?(borderRightStyle : string option)
  ?(borderBottomStyle : string option)
  ?(borderLeftStyle : string option)
  ?(borderTopWidth : string option)
  ?(borderRightWidth : string option)
  ?(borderBottomWidth : string option)
  ?(borderLeftWidth : string option)
  ?(borderWidth : string option)
  ?(bottom : string option)
  ?(captionSide : string option)
  ?(clear : string option)
  ?(color : string option)
  ?(content : string option)
  ?(counterIncrement : string option)
  ?(counterReset : string option)
  ?(cue : string option)
  ?(cueAfter : string option)
  ?(cueBefore : string option)
  ?(cursor : string option)
  ?(direction : string option)
  ?(display : string option)
  ?(elevation : string option)
  ?(emptyCells : string option)
  ?(float : string option)
  ?(font : string option)
  ?(fontFamily : string option)
  ?(fontSize : string option)
  ?(fontSizeAdjust : string option)
  ?(fontStretch : string option)
  ?(fontStyle : string option)
  ?(fontVariant : string option)
  ?(fontWeight : string option)
  ?(height : string option)
  ?(left : string option)
  ?(letterSpacing : string option)
  ?(lineHeight : string option)
  ?(listStyle : string option)
  ?(listStyleImage : string option)
  ?(listStylePosition : string option)
  ?(listStyleType : string option)
  ?(margin : string option)
  ?(marginTop : string option)
  ?(marginRight : string option)
  ?(marginBottom : string option)
  ?(marginLeft : string option)
  ?(markerOffset : string option)
  ?(marks : string option)
  ?(maxHeight : string option)
  ?(maxWidth : string option)
  ?(minHeight : string option)
  ?(minWidth : string option)
  ?(orphans : string option)
  ?(outline : string option)
  ?(outlineColor : string option)
  ?(outlineStyle : string option)
  ?(outlineWidth : string option)
  ?(overflow : string option)
  ?(overflowX : string option)
  ?(overflowY : string option)
  ?(padding : string option)
  ?(paddingTop : string option)
  ?(paddingRight : string option)
  ?(paddingBottom : string option)
  ?(paddingLeft : string option)
  ?(page : string option)
  ?(pageBreakAfter : string option)
  ?(pageBreakBefore : string option)
  ?(pageBreakInside : string option)
  ?(pause : string option)
  ?(pauseAfter : string option)
  ?(pauseBefore : string option)
  ?(pitch : string option)
  ?(pitchRange : string option)
  ?(playDuring : string option)
  ?(position : string option)
  ?(quotes : string option)
  ?(richness : string option)
  ?(right : string option)
  ?(size : string option)
  ?(speak : string option)
  ?(speakHeader : string option)
  ?(speakNumeral : string option)
  ?(speakPunctuation : string option)
  ?(speechRate : string option)
  ?(stress : string option)
  ?(tableLayout : string option)
  ?(textAlign : string option)
  ?(textDecoration : string option)
  ?(textIndent : string option)
  ?(textShadow : string option)
  ?(textTransform : string option)
  ?(top : string option)
  ?(unicodeBidi : string option)
  ?(verticalAlign : string option)
  ?(visibility : string option)
  ?(voiceFamily : string option)
  ?(volume : string option)
  ?(whiteSpace : string option)
  ?(widows : string option)
  ?(width : string option)
  ?(wordSpacing : string option)
  ?(zIndex : string option)
  ?(opacity : string option)
  ?(backgroundOrigin : string option)
  ?(backgroundSize : string option)
  ?(backgroundClip : string option)
  ?(borderRadius : string option)
  ?(borderTopLeftRadius : string option)
  ?(borderTopRightRadius : string option)
  ?(borderBottomLeftRadius : string option)
  ?(borderBottomRightRadius : string option)
  ?(borderImage : string option)
  ?(borderImageSource : string option)
  ?(borderImageSlice : string option)
  ?(borderImageWidth : string option)
  ?(borderImageOutset : string option)
  ?(borderImageRepeat : string option)
  ?(boxShadow : string option)
  ?(columns : string option)
  ?(columnCount : string option)
  ?(columnFill : string option)
  ?(columnGap : string option)
  ?(columnRule : string option)
  ?(columnRuleColor : string option)
  ?(columnRuleStyle : string option)
  ?(columnRuleWidth : string option)
  ?(columnSpan : string option)
  ?(columnWidth : string option)
  ?(breakAfter : string option)
  ?(breakBefore : string option)
  ?(breakInside : string option)
  ?(rest : string option)
  ?(restAfter : string option)
  ?(restBefore : string option)
  ?(speakAs : string option)
  ?(voiceBalance : string option)
  ?(voiceDuration : string option)
  ?(voicePitch : string option)
  ?(voiceRange : string option)
  ?(voiceRate : string option)
  ?(voiceStress : string option)
  ?(voiceVolume : string option)
  ?(objectFit : string option)
  ?(objectPosition : string option)
  ?(imageResolution : string option)
  ?(imageOrientation : string option)
  ?(alignContent : string option)
  ?(alignItems : string option)
  ?(alignSelf : string option)
  ?(flex : string option)
  ?(flexBasis : string option)
  ?(flexDirection : string option)
  ?(flexFlow : string option)
  ?(flexGrow : string option)
  ?(flexShrink : string option)
  ?(flexWrap : string option)
  ?(justifyContent : string option)
  ?(order : string option)
  ?(textDecorationColor : string option)
  ?(textDecorationLine : string option)
  ?(textDecorationSkip : string option)
  ?(textDecorationStyle : string option)
  ?(textEmphasis : string option)
  ?(textEmphasisColor : string option)
  ?(textEmphasisPosition : string option)
  ?(textEmphasisStyle : string option)
  ?(textUnderlinePosition : string option)
  ?(fontFeatureSettings : string option)
  ?(fontKerning : string option)
  ?(fontLanguageOverride : string option)
  ?(fontSynthesis : string option)
  ?(forntVariantAlternates : string option)
  ?(fontVariantCaps : string option)
  ?(fontVariantEastAsian : string option)
  ?(fontVariantLigatures : string option)
  ?(fontVariantNumeric : string option)
  ?(fontVariantPosition : string option)
  ?(all : string option)
  ?(textCombineUpright : string option)
  ?(textOrientation : string option)
  ?(writingMode : string option)
  ?(shapeImageThreshold : string option)
  ?(shapeMargin : string option)
  ?(shapeOutside : string option)
  ?(mask : string option)
  ?(maskBorder : string option)
  ?(maskBorderMode : string option)
  ?(maskBorderOutset : string option)
  ?(maskBorderRepeat : string option)
  ?(maskBorderSlice : string option)
  ?(maskBorderSource : string option)
  ?(maskBorderWidth : string option)
  ?(maskClip : string option)
  ?(maskComposite : string option)
  ?(maskImage : string option)
  ?(maskMode : string option)
  ?(maskOrigin : string option)
  ?(maskPosition : string option)
  ?(maskRepeat : string option)
  ?(maskSize : string option)
  ?(maskType : string option)
  ?(backgroundBlendMode : string option)
  ?(isolation : string option)
  ?(mixBlendMode : string option)
  ?(boxDecorationBreak : string option)
  ?(boxSizing : string option)
  ?(caretColor : string option)
  ?(navDown : string option)
  ?(navLeft : string option)
  ?(navRight : string option)
  ?(navUp : string option)
  ?(outlineOffset : string option)
  ?(resize : string option)
  ?(textOverflow : string option)
  ?(grid : string option)
  ?(gridArea : string option)
  ?(gridAutoColumns : string option)
  ?(gridAutoFlow : string option)
  ?(gridAutoRows : string option)
  ?(gridColumn : string option)
  ?(gridColumnEnd : string option)
  ?(gridColumnGap : string option)
  ?(gridColumnStart : string option)
  ?(gridGap : string option)
  ?(gridRow : string option)
  ?(gridRowEnd : string option)
  ?(gridRowGap : string option)
  ?(gridRowStart : string option)
  ?(gridTemplate : string option)
  ?(gridTemplateAreas : string option)
  ?(gridTemplateColumns : string option)
  ?(gridTemplateRows : string option)
  ?(willChange : string option)
  ?(hangingPunctuation : string option)
  ?(hyphens : string option)
  ?(lineBreak : string option)
  ?(overflowWrap : string option)
  ?(tabSize : string option)
  ?(textAlignLast : string option)
  ?(textJustify : string option)
  ?(wordBreak : string option)
  ?(wordWrap : string option)
  ?(animation : string option)
  ?(animationDelay : string option)
  ?(animationDirection : string option)
  ?(animationDuration : string option)
  ?(animationFillMode : string option)
  ?(animationIterationCount : string option)
  ?(animationName : string option)
  ?(animationPlayState : string option)
  ?(animationTimingFunction : string option)
  ?(transition : string option)
  ?(transitionDelay : string option)
  ?(transitionDuration : string option)
  ?(transitionProperty : string option)
  ?(transitionTimingFunction : string option)
  ?(backfaceVisibility : string option)
  ?(perspective : string option)
  ?(perspectiveOrigin : string option)
  ?(transform : string option)
  ?(transformOrigin : string option)
  ?(transformStyle : string option)
  ?(justifyItems : string option)
  ?(justifySelf : string option)
  ?(placeContent : string option)
  ?(placeItems : string option)
  ?(placeSelf : string option)
  ?(appearance : string option)
  ?(caret : string option)
  ?(caretAnimation : string option)
  ?(caretShape : string option)
  ?(userSelect : string option)
  ?(maxLines : string option)
  ?(marqueeDirection : string option)
  ?(marqueeLoop : string option)
  ?(marqueeSpeed : string option)
  ?(marqueeStyle : string option)
  ?(overflowStyle : string option)
  ?(rotation : string option)
  ?(rotationPoint : string option)
  ?(alignmentBaseline : string option)
  ?(baselineShift : string option)
  ?(clip : string option)
  ?(clipPath : string option)
  ?(clipRule : string option)
  ?(colorInterpolation : string option)
  ?(colorInterpolationFilters : string option)
  ?(colorProfile : string option)
  ?(colorRendering : string option)
  ?(dominantBaseline : string option)
  ?(fill : string option)
  ?(fillOpacity : string option)
  ?(fillRule : string option)
  ?(filter : string option)
  ?(floodColor : string option)
  ?(floodOpacity : string option)
  ?(glyphOrientationHorizontal : string option)
  ?(glyphOrientationVertical : string option)
  ?(imageRendering : string option)
  ?(kerning : string option)
  ?(lightingColor : string option)
  ?(markerEnd : string option)
  ?(markerMid : string option)
  ?(markerStart : string option)
  ?(pointerEvents : string option)
  ?(shapeRendering : string option)
  ?(stopColor : string option)
  ?(stopOpacity : string option)
  ?(stroke : string option)
  ?(strokeDasharray : string option)
  ?(strokeDashoffset : string option)
  ?(strokeLinecap : string option)
  ?(strokeLinejoin : string option)
  ?(strokeMiterlimit : string option)
  ?(strokeOpacity : string option)
  ?(strokeWidth : string option)
  ?(textAnchor : string option)
  ?(textRendering : string option)
  ?(rubyAlign : string option)
  ?(rubyMerge : string option)
  ?(rubyPosition : string option)
  () =
  (* 
     The order of addition matters since it will need to be the same order as
  the JS object defined in https://github.com/reasonml/reason-react/blob/3327dc214905c4b2863b19807aaac375633645cf/src/dOMStyle.re 

  The following shell script can be run from the reason-react repository to generate the calls to "add" below:

  for style in $(cat src/dOMStyle.re | grep "~" | sed 's/.*\~\([^:]*\):.*/\1/'); do
    dashed=$(echo "$style" | sed 's/\([A-Z]\)/-\L\1/g')
    echo "|> add \"$dashed\" $style"
  done

  *)
  []
  |> add "azimuth" azimuth
  |> add "background" background
  |> add "background-attachment" backgroundAttachment
  |> add "background-color" backgroundColor
  |> add "background-image" backgroundImage
  |> add "background-position" backgroundPosition
  |> add "background-repeat" backgroundRepeat
  |> add "border" border
  |> add "border-collapse" borderCollapse
  |> add "border-color" borderColor
  |> add "border-spacing" borderSpacing
  |> add "border-style" borderStyle
  |> add "border-top" borderTop
  |> add "border-right" borderRight
  |> add "border-bottom" borderBottom
  |> add "border-left" borderLeft
  |> add "border-top-color" borderTopColor
  |> add "border-right-color" borderRightColor
  |> add "border-bottom-color" borderBottomColor
  |> add "border-left-color" borderLeftColor
  |> add "border-top-style" borderTopStyle
  |> add "border-right-style" borderRightStyle
  |> add "border-bottom-style" borderBottomStyle
  |> add "border-left-style" borderLeftStyle
  |> add "border-top-width" borderTopWidth
  |> add "border-right-width" borderRightWidth
  |> add "border-bottom-width" borderBottomWidth
  |> add "border-left-width" borderLeftWidth
  |> add "border-width" borderWidth
  |> add "bottom" bottom
  |> add "caption-side" captionSide
  |> add "clear" clear
  |> add "clip" clip
  |> add "color" color
  |> add "content" content
  |> add "counter-increment" counterIncrement
  |> add "counter-reset" counterReset
  |> add "cue" cue
  |> add "cue-after" cueAfter
  |> add "cue-before" cueBefore
  |> add "cursor" cursor
  |> add "direction" direction
  |> add "display" display
  |> add "elevation" elevation
  |> add "empty-cells" emptyCells
  |> add "float" float
  |> add "font" font
  |> add "font-family" fontFamily
  |> add "font-size" fontSize
  |> add "font-size-adjust" fontSizeAdjust
  |> add "font-stretch" fontStretch
  |> add "font-style" fontStyle
  |> add "font-variant" fontVariant
  |> add "font-weight" fontWeight
  |> add "height" height
  |> add "left" left
  |> add "letter-spacing" letterSpacing
  |> add "line-height" lineHeight
  |> add "list-style" listStyle
  |> add "list-style-image" listStyleImage
  |> add "list-style-position" listStylePosition
  |> add "list-style-type" listStyleType
  |> add "margin" margin
  |> add "margin-top" marginTop
  |> add "margin-right" marginRight
  |> add "margin-bottom" marginBottom
  |> add "margin-left" marginLeft
  |> add "marker-offset" markerOffset
  |> add "marks" marks
  |> add "max-height" maxHeight
  |> add "max-width" maxWidth
  |> add "min-height" minHeight
  |> add "min-width" minWidth
  |> add "orphans" orphans
  |> add "outline" outline
  |> add "outline-color" outlineColor
  |> add "outline-style" outlineStyle
  |> add "outline-width" outlineWidth
  |> add "overflow" overflow
  |> add "overflow-x" overflowX
  |> add "overflow-y" overflowY
  |> add "padding" padding
  |> add "padding-top" paddingTop
  |> add "padding-right" paddingRight
  |> add "padding-bottom" paddingBottom
  |> add "padding-left" paddingLeft
  |> add "page" page
  |> add "page-break-after" pageBreakAfter
  |> add "page-break-before" pageBreakBefore
  |> add "page-break-inside" pageBreakInside
  |> add "pause" pause
  |> add "pause-after" pauseAfter
  |> add "pause-before" pauseBefore
  |> add "pitch" pitch
  |> add "pitch-range" pitchRange
  |> add "play-during" playDuring
  |> add "position" position
  |> add "quotes" quotes
  |> add "richness" richness
  |> add "right" right
  |> add "size" size
  |> add "speak" speak
  |> add "speak-header" speakHeader
  |> add "speak-numeral" speakNumeral
  |> add "speak-punctuation" speakPunctuation
  |> add "speech-rate" speechRate
  |> add "stress" stress
  |> add "table-layout" tableLayout
  |> add "text-align" textAlign
  |> add "text-decoration" textDecoration
  |> add "text-indent" textIndent
  |> add "text-shadow" textShadow
  |> add "text-transform" textTransform
  |> add "top" top
  |> add "unicode-bidi" unicodeBidi
  |> add "vertical-align" verticalAlign
  |> add "visibility" visibility
  |> add "voice-family" voiceFamily
  |> add "volume" volume
  |> add "white-space" whiteSpace
  |> add "widows" widows
  |> add "width" width
  |> add "word-spacing" wordSpacing
  |> add "z-index" zIndex
  |> add "opacity" opacity
  |> add "background-origin" backgroundOrigin
  |> add "background-size" backgroundSize
  |> add "background-clip" backgroundClip
  |> add "border-radius" borderRadius
  |> add "border-top-left-radius" borderTopLeftRadius
  |> add "border-top-right-radius" borderTopRightRadius
  |> add "border-bottom-left-radius" borderBottomLeftRadius
  |> add "border-bottom-right-radius" borderBottomRightRadius
  |> add "border-image" borderImage
  |> add "border-image-source" borderImageSource
  |> add "border-image-slice" borderImageSlice
  |> add "border-image-width" borderImageWidth
  |> add "border-image-outset" borderImageOutset
  |> add "border-image-repeat" borderImageRepeat
  |> add "box-shadow" boxShadow
  |> add "columns" columns
  |> add "column-count" columnCount
  |> add "column-fill" columnFill
  |> add "column-gap" columnGap
  |> add "column-rule" columnRule
  |> add "column-rule-color" columnRuleColor
  |> add "column-rule-style" columnRuleStyle
  |> add "column-rule-width" columnRuleWidth
  |> add "column-span" columnSpan
  |> add "column-width" columnWidth
  |> add "break-after" breakAfter
  |> add "break-before" breakBefore
  |> add "break-inside" breakInside
  |> add "rest" rest
  |> add "rest-after" restAfter
  |> add "rest-before" restBefore
  |> add "speak-as" speakAs
  |> add "voice-balance" voiceBalance
  |> add "voice-duration" voiceDuration
  |> add "voice-pitch" voicePitch
  |> add "voice-range" voiceRange
  |> add "voice-rate" voiceRate
  |> add "voice-stress" voiceStress
  |> add "voice-volume" voiceVolume
  |> add "object-fit" objectFit
  |> add "object-position" objectPosition
  |> add "image-resolution" imageResolution
  |> add "image-orientation" imageOrientation
  |> add "align-content" alignContent
  |> add "align-items" alignItems
  |> add "align-self" alignSelf
  |> add "flex" flex
  |> add "flex-basis" flexBasis
  |> add "flex-direction" flexDirection
  |> add "flex-flow" flexFlow
  |> add "flex-grow" flexGrow
  |> add "flex-shrink" flexShrink
  |> add "flex-wrap" flexWrap
  |> add "justify-content" justifyContent
  |> add "order" order
  |> add "text-decoration-color" textDecorationColor
  |> add "text-decoration-line" textDecorationLine
  |> add "text-decoration-skip" textDecorationSkip
  |> add "text-decoration-style" textDecorationStyle
  |> add "text-emphasis" textEmphasis
  |> add "text-emphasis-color" textEmphasisColor
  |> add "text-emphasis-position" textEmphasisPosition
  |> add "text-emphasis-style" textEmphasisStyle
  |> add "text-underline-position" textUnderlinePosition
  |> add "font-feature-settings" fontFeatureSettings
  |> add "font-kerning" fontKerning
  |> add "font-language-override" fontLanguageOverride
  |> add "font-synthesis" fontSynthesis
  |> add "fornt-variant-alternates" forntVariantAlternates
  |> add "font-variant-caps" fontVariantCaps
  |> add "font-variant-east-asian" fontVariantEastAsian
  |> add "font-variant-ligatures" fontVariantLigatures
  |> add "font-variant-numeric" fontVariantNumeric
  |> add "font-variant-position" fontVariantPosition
  |> add "all" all
  |> add "glyph-orientation-vertical" glyphOrientationVertical
  |> add "text-combine-upright" textCombineUpright
  |> add "text-orientation" textOrientation
  |> add "writing-mode" writingMode
  |> add "shape-image-threshold" shapeImageThreshold
  |> add "shape-margin" shapeMargin
  |> add "shape-outside" shapeOutside
  |> add "clip-path" clipPath
  |> add "clip-rule" clipRule
  |> add "mask" mask
  |> add "mask-border" maskBorder
  |> add "mask-border-mode" maskBorderMode
  |> add "mask-border-outset" maskBorderOutset
  |> add "mask-border-repeat" maskBorderRepeat
  |> add "mask-border-slice" maskBorderSlice
  |> add "mask-border-source" maskBorderSource
  |> add "mask-border-width" maskBorderWidth
  |> add "mask-clip" maskClip
  |> add "mask-composite" maskComposite
  |> add "mask-image" maskImage
  |> add "mask-mode" maskMode
  |> add "mask-origin" maskOrigin
  |> add "mask-position" maskPosition
  |> add "mask-repeat" maskRepeat
  |> add "mask-size" maskSize
  |> add "mask-type" maskType
  |> add "background-blend-mode" backgroundBlendMode
  |> add "isolation" isolation
  |> add "mix-blend-mode" mixBlendMode
  |> add "box-decoration-break" boxDecorationBreak
  |> add "box-sizing" boxSizing
  |> add "caret-color" caretColor
  |> add "nav-down" navDown
  |> add "nav-left" navLeft
  |> add "nav-right" navRight
  |> add "nav-up" navUp
  |> add "outline-offset" outlineOffset
  |> add "resize" resize
  |> add "text-overflow" textOverflow
  |> add "grid" grid
  |> add "grid-area" gridArea
  |> add "grid-auto-columns" gridAutoColumns
  |> add "grid-auto-flow" gridAutoFlow
  |> add "grid-auto-rows" gridAutoRows
  |> add "grid-column" gridColumn
  |> add "grid-column-end" gridColumnEnd
  |> add "grid-column-gap" gridColumnGap
  |> add "grid-column-start" gridColumnStart
  |> add "grid-gap" gridGap
  |> add "grid-row" gridRow
  |> add "grid-row-end" gridRowEnd
  |> add "grid-row-gap" gridRowGap
  |> add "grid-row-start" gridRowStart
  |> add "grid-template" gridTemplate
  |> add "grid-template-areas" gridTemplateAreas
  |> add "grid-template-columns" gridTemplateColumns
  |> add "grid-template-rows" gridTemplateRows
  |> add "will-change" willChange
  |> add "hanging-punctuation" hangingPunctuation
  |> add "hyphens" hyphens
  |> add "line-break" lineBreak
  |> add "overflow-wrap" overflowWrap
  |> add "tab-size" tabSize
  |> add "text-align-last" textAlignLast
  |> add "text-justify" textJustify
  |> add "word-break" wordBreak
  |> add "word-wrap" wordWrap
  |> add "animation" animation
  |> add "animation-delay" animationDelay
  |> add "animation-direction" animationDirection
  |> add "animation-duration" animationDuration
  |> add "animation-fill-mode" animationFillMode
  |> add "animation-iteration-count" animationIterationCount
  |> add "animation-name" animationName
  |> add "animation-play-state" animationPlayState
  |> add "animation-timing-function" animationTimingFunction
  |> add "transition" transition
  |> add "transition-delay" transitionDelay
  |> add "transition-duration" transitionDuration
  |> add "transition-property" transitionProperty
  |> add "transition-timing-function" transitionTimingFunction
  |> add "backface-visibility" backfaceVisibility
  |> add "perspective" perspective
  |> add "perspective-origin" perspectiveOrigin
  |> add "transform" transform
  |> add "transform-origin" transformOrigin
  |> add "transform-style" transformStyle
  |> add "justify-items" justifyItems
  |> add "justify-self" justifySelf
  |> add "place-content" placeContent
  |> add "place-items" placeItems
  |> add "place-self" placeSelf
  |> add "appearance" appearance
  |> add "caret" caret
  |> add "caret-animation" caretAnimation
  |> add "caret-shape" caretShape
  |> add "user-select" userSelect
  |> add "max-lines" maxLines
  |> add "marquee-direction" marqueeDirection
  |> add "marquee-loop" marqueeLoop
  |> add "marquee-speed" marqueeSpeed
  |> add "marquee-style" marqueeStyle
  |> add "overflow-style" overflowStyle
  |> add "rotation" rotation
  |> add "rotation-point" rotationPoint
  |> add "alignment-baseline" alignmentBaseline
  |> add "baseline-shift" baselineShift
  |> add "clip" clip
  |> add "clip-path" clipPath
  |> add "clip-rule" clipRule
  |> add "color-interpolation" colorInterpolation
  |> add "color-interpolation-filters" colorInterpolationFilters
  |> add "color-profile" colorProfile
  |> add "color-rendering" colorRendering
  |> add "cursor" cursor
  |> add "dominant-baseline" dominantBaseline
  |> add "fill" fill
  |> add "fill-opacity" fillOpacity
  |> add "fill-rule" fillRule
  |> add "filter" filter
  |> add "flood-color" floodColor
  |> add "flood-opacity" floodOpacity
  |> add "glyph-orientation-horizontal" glyphOrientationHorizontal
  |> add "glyph-orientation-vertical" glyphOrientationVertical
  |> add "image-rendering" imageRendering
  |> add "kerning" kerning
  |> add "lighting-color" lightingColor
  |> add "marker-end" markerEnd
  |> add "marker-mid" markerMid
  |> add "marker-start" markerStart
  |> add "pointer-events" pointerEvents
  |> add "shape-rendering" shapeRendering
  |> add "stop-color" stopColor
  |> add "stop-opacity" stopOpacity
  |> add "stroke" stroke
  |> add "stroke-dasharray" strokeDasharray
  |> add "stroke-dashoffset" strokeDashoffset
  |> add "stroke-linecap" strokeLinecap
  |> add "stroke-linejoin" strokeLinejoin
  |> add "stroke-miterlimit" strokeMiterlimit
  |> add "stroke-opacity" strokeOpacity
  |> add "stroke-width" strokeWidth
  |> add "text-anchor" textAnchor
  |> add "text-rendering" textRendering
  |> add "ruby-align" rubyAlign
  |> add "ruby-merge" rubyMerge
  |> add "ruby-position" rubyPosition
[@@@ocamlformat "enable"]

let to_string (styles : t) : string =
  let size = List.length styles in
  let buff = Buffer.create size in
  List.rev styles |> List.to_seq
  |> Seq.iteri (fun index (k, v) ->
         if index == size - 1 then (
           Buffer.add_string buff k;
           Buffer.add_string buff ":";
           Buffer.add_string buff (String.trim v))
         else (
           Buffer.add_string buff k;
           Buffer.add_string buff ":";
           Buffer.add_string buff (String.trim v);
           Buffer.add_string buff ";"));
  Buffer.contents buff

let combine (styles1 : t) (styles2 : t) : t =
  let seq1 = styles1 |> List.to_seq in
  let seq2 = styles2 |> List.to_seq in
  Seq.append seq1 seq2 |> List.of_seq

let string_of_chars chars =
  let buf = Buffer.create 16 in
  List.iter (Buffer.add_char buf) chars;
  Buffer.contents buf

let chars_of_string str = List.init (String.length str) (String.get str)

let camelcaseToKebabcase str =
  let rec loop acc = function
    | [] -> acc
    | [ x ] -> x :: acc
    | x :: y :: xs ->
        if Char.uppercase_ascii y == y then
          loop ('-' :: x :: acc) (Char.lowercase_ascii y :: xs)
        else loop (x :: acc) (y :: xs)
  in
  str |> chars_of_string |> loop [] |> List.rev |> string_of_chars

let unsafeAddProp styles (key : string) (value : string) : t =
  (* Adds the (key,value) into last position *)
  (camelcaseToKebabcase key, value) :: styles

(* Since we don't have a proper representation of `< .. > Js.t` yet,
   we can't make the unsafeAddStyle

   external unsafeAddStyle :
      ((_)[@mel.as {json|{}|json}]) -> t -> < .. > Js.t -> t = "Object.assign" *)
