#!/bin/sh
# Extracts the public API surface (module + value names) of Melange's Js and
# Belt libraries into TSV files committed in the repo:
#
#   packages/Js/melange-surface.tsv
#   packages/Belt/melange-surface.tsv
#
# Format: <Module>\t<value-name>, sorted. A line with only <Module> and the
# marker "(module)" records a module that exists in Melange with no extracted
# values (type-only, cppo-generated, or intentionally skipped).
#
# Run this when bumping the melange dependency, then review the diff.
# Requires the melange sources in the opam switch cache
# (_opam/.opam-switch/sources/melange.<version>).

set -eu

root=$(cd "$(dirname "$0")/../.." && pwd)

src=$(ls -d "$root"/_opam/.opam-switch/sources/melange.* 2>/dev/null | head -n 1 || true)
if [ -z "$src" ]; then
  echo "error: melange sources not found in _opam/.opam-switch/sources." >&2
  echo "hint: run 'opam install melange --keep-build-dir' or 'opam source melange'." >&2
  exit 1
fi

version=$(basename "$src" | sed 's/^melange\.//')

# Extract top-level `val`, `external` and `let` names from an OCaml source.
# Only column-0 declarations outside comments are considered, which is how the
# melange runtime sources are formatted; indented declarations belong to
# nested modules. Comment tracking avoids picking up `{[ ... ]}` doc examples.
extract_values() {
  awk '
    {
      if (depth == 0 && $0 ~ /^(val|external|let)[ \t]/) {
        name = $2
        # `let rec f`
        if (name == "rec") name = $3
        # strip any trailing `:`/`=` glued to the name
        sub(/[:=(].*$/, "", name)
        # skip destructuring / unit bindings / operators
        if (name ~ /^[a-z_][a-zA-Z0-9_'\''"]*$/ && name != "_") print name
      }
      line = $0
      while (match(line, /\(\*|\*\)/)) {
        if (substr(line, RSTART, 2) == "(*") depth++
        else if (depth > 0) depth--
        line = substr(line, RSTART + 2)
      }
    }
  ' "$1"
}

# ---------------------------------------------------------------------------
# Js
# ---------------------------------------------------------------------------

js_out="$root/packages/Js/melange-surface.tsv"
{
  echo "# melange $version — generated by scripts/status/extract_melange_surface.sh"

  runtime="$src/jscomp/runtime"

  # Top-level Js values come from the installed (cppo-expanded) js.mli.
  installed_js_mli="$root/_opam/lib/melange/js/js.mli"
  if [ -f "$installed_js_mli" ]; then
    extract_values "$installed_js_mli" | while read -r name; do
      printf 'Js\t%s\n' "$name"
    done
  fi

  for f in "$runtime"/js_*.ml; do
    base=$(basename "$f" .ml)
    case "$base" in
      js_mapper_runtime | js_OO) continue ;; # internal machinery
      *.cppo) continue ;;
    esac
    # Module name: js_string -> String, js_formData -> FormData
    mod=$(echo "$base" | sed 's/^js_//')
    case "$mod" in
      weakmap) mod=WeakMap ;;
      weakset) mod=WeakSet ;;
      *) mod=$(echo "$mod" | awk '{ print toupper(substr($0,1,1)) substr($0,2) }') ;;
    esac
    # Prefer the .mli when melange ships one.
    decl="$f"
    [ -f "${f}i" ] && decl="${f}i"
    values=$(extract_values "$decl")
    if [ -n "$values" ]; then
      echo "$values" | while read -r name; do
        printf 'Js.%s\t%s\n' "$mod" "$name"
      done
    else
      printf 'Js.%s\t(module)\n' "$mod"
    fi
  done

  # cppo-generated module: record its existence without value extraction.
  [ -f "$runtime/js_typed_array.cppo.ml" ] && printf 'Js.Typed_array\t(module)\n'
} | awk 'NR == 1 { print; next } { print | "sort -u" }' >"$js_out"

# ---------------------------------------------------------------------------
# Belt
# ---------------------------------------------------------------------------

belt_out="$root/packages/Belt/melange-surface.tsv"
{
  echo "# melange $version — generated by scripts/status/extract_melange_surface.sh"

  # Use the installed (cppo-expanded) interfaces: the source tree keeps
  # HashMap/Map/Set Int+String variants as pre-cppo templates.
  for f in "$root"/_opam/lib/melange/belt/belt_*.mli; do
    base=$(basename "$f" .mli)
    case "$base" in
      belt_internal* | *.cppo) continue ;;
    esac
    # belt_HashMapString -> Belt.HashMap.String, belt_MapDict -> Belt.Map.Dict, etc.
    mod=$(echo "$base" | sed 's/^belt_//')
    mod=$(echo "$mod" | sed -E \
      -e 's/^(HashMap|HashSet|MutableMap|MutableSet|SortArray|Map|Set)(Int|String|Dict)$/\1.\2/')
    values=$(extract_values "$f")
    if [ -n "$values" ]; then
      echo "$values" | while read -r name; do
        printf 'Belt.%s\t%s\n' "$mod" "$name"
      done
    else
      printf 'Belt.%s\t(module)\n' "$mod"
    fi
  done
} | awk 'NR == 1 { print; next } { print | "sort -u" }' >"$belt_out"

echo "wrote $js_out"
echo "wrote $belt_out"
